version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v3.6.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - prometheus-net
    ports:
      - "9090:9090"

  node-exporter:
    image: prom/node-exporter:v1.9.1
    networks:
      - prometheus-net
    ports:
      - "9100:9100"

networks:
  prometheus-net:
    driver: bridge

volumes:
  prometheus_data:
